---
- name: Converge
  hosts: all
  vars:
    snapraid_data_disks:
      - name: data1
        path: /mnt/data1
      - name: data2
        path: /mnt/data2
      - name: data3
        path: /mnt/data3
    snapraid_parity_disks:
      - path: /mnt/parity1
      - path: /mnt/parity2
    snapraid_content_files:
      - /mnt/data1/snapraid.content
      - /mnt/data2/snapraid.content
      - /mnt/data3/snapraid.content
    snapraid_exclude_hidden: yes
    snapraid_excludes:
      - /tmp/
      - /lost+found/
    snapraid_blocksize: 512
    snapraid_hashsize: 16
    snapraid_autosave: 1
  roles:
    - role: ansible-role-snapraid
