---
- name: Prepare
  hosts: all
  tasks:
    - name: Create directories
      become: yes
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /mnt/data1
        - /mnt/data2
        - /mnt/parity1
        - /mnt/parity2

    - name: Create data files
      become: yes
      copy:
        content: "{{ item.content }}\n"
        dest: "{{ item.path }}"
      loop:
        - path: /mnt/data1/file1.txt
          content: test1
        - path: /mnt/data2/file2.txt
          content: test2
