---
- name: Prepare
  hosts: all
  tasks:
    - name: Create data files
      become: true
      copy:
        content: "{{ item.content }}\n"
        dest: "{{ item.path }}"
      loop:
        - path: /mnt/data1/file1.txt
          content: test1
        - path: /mnt/data2/file2.txt
          content: test2
        - path: /mnt/data3/file3.txt
          content: test3
