---
name: CI
"on":
  push:
  schedule:
    - cron: "0 4 * * 1"

jobs:
  # test the role
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - geerlingguy/docker-ubuntu2004-ansible
          - geerlingguy/docker-ubuntu1804-ansible
          - geerlingguy/docker-ubuntu1604-ansible
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.in

      - name: Run molecule tests
        env:
          IMAGE: ${{ matrix.image }}
        run: molecule -v test

  # publish the role on ansible galaxy
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
